2024-12-19 20:21:42,069 - utils - ERROR - Error loading config: [Errno 2] No such file or directory: 'config.yaml'
2024-12-19 20:21:42,073 - __main__ - ERROR - Error in main execution: [Errno 2] No such file or directory: 'config.yaml'
Traceback (most recent call last):
  File "/share/home/lsy_chenyanchao/projects/model_test/scr/main.py", line 177, in <module>
    main(args.config, args.mode)
  File "/share/home/lsy_chenyanchao/projects/model_test/scr/main.py", line 74, in main
    config = Utils.load_config(config_path)
  File "/share/home/lsy_chenyanchao/projects/model_test/scr/utils.py", line 41, in load_config
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
Traceback (most recent call last):
  File "/share/home/lsy_chenyanchao/projects/model_test/scr/main.py", line 177, in <module>
    main(args.config, args.mode)
  File "/share/home/lsy_chenyanchao/projects/model_test/scr/main.py", line 74, in main
    config = Utils.load_config(config_path)
  File "/share/home/lsy_chenyanchao/projects/model_test/scr/utils.py", line 41, in load_config
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
